version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hidden_heritage_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hidden_heritage
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init_mysql:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo:6.0
    container_name: hidden_heritage_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./database/init_mongo:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
  mongo_data:
